version: '3'
services:
  selenium:
    image: seleniarm/standalone-chromium
    shm_size: '2gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client
  node:
    image: node:19
    volumes:
      - ./:/project
    working_dir: /project
    tty: true
