name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: "[Backend] Install"
        working-directory: ./backend
        run: poetry install

      - name: "[Backend] Run flake8"
        working-directory: ./backend
        run: poetry run flake8

      - name: "[Backend] Run unit tests"
        working-directory: ./backend
        run: poetry run pytest tests/ --cov=app --cov-report=term --cov-fail-under=85

      - name: "[Frontend] Install"
        working-directory: ./frontend
        run: poetry install

      - name: "[Frontend] Run flake8"
        working-directory: ./frontend
        run: poetry run flake8

      - name: "[Frontend] Run unit tests"
        working-directory: ./frontend
        run: poetry run pytest tests/ --cov=. --cov-report=term --cov-fail-under=85

  sonarqube_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: "[Backend] Install"
        working-directory: ./backend
        run: poetry install

      - name: "[Backend] Coverage reports"
        working-directory: ./backend
        run: poetry run pytest tests/ --cov=app --cov-report=xml

      - name: "[Frontend] Install"
        working-directory: ./frontend
        run: poetry install

      - name: "[Frontend] Coverage reports"
        working-directory: ./frontend
        run: poetry run pytest tests/ --cov=. --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Security Scanning
        run: |
          # Integrate Snyk or SonarQube security scanning command here.

  ui_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run UI tests
        run: |
          # Integrate Selenium test execution command here.

  performance_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Perform performance testing
        run: |
          # Integrate performance testing command here.

  capacity_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Capacity Testing
        run: |
          # Integrate k6 capacity testing command here.
